## Documentation: http://docs.travis-ci.org/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.3
  - nightly
codecov: true
notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
jobs:
  allow_failures:
  - julia: nightly
  - os: osx

addons:
  apt_packages:
    - gfortran

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - julia --project --color=yes -e "import Pkg; Pkg.build(); Pkg.instantiate()"
  - julia --project --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true);"
  - kill %1
  - echo "Test successful."

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes -e 'include("docs/make.jl")'
      after_success: skip
